// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ5n0mAk2DaNjY_lCoJneioO4Olrc1R1s',
    appId: '1:532513795521:web:2b0e09fac817a3b7539340',
    messagingSenderId: '532513795521',
    projectId: 'semesterproject-74b73',
    authDomain: 'semesterproject-74b73.firebaseapp.com',
    storageBucket: 'semesterproject-74b73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE6HL8e5JrRXxD2Or8XFhPtnWbgtehUvM',
    appId: '1:532513795521:android:91e6beabca909fff539340',
    messagingSenderId: '532513795521',
    projectId: 'semesterproject-74b73',
    storageBucket: 'semesterproject-74b73.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ5n0mAk2DaNjY_lCoJneioO4Olrc1R1s',
    appId: '1:532513795521:web:b1a6063c73477b7a539340',
    messagingSenderId: '532513795521',
    projectId: 'semesterproject-74b73',
    authDomain: 'semesterproject-74b73.firebaseapp.com',
    storageBucket: 'semesterproject-74b73.appspot.com',
  );
}
